SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES* A.PRICE)  AS TOTAL_SALES
FROM BOOK AS A LEFT JOIN
AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID LEFT JOIN 
BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC
