SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO
WHERE ID IN (SELECT A.ID
            FROM FISH_INFO A 
             INNER JOIN FISH_NAME_INFO B
             ON A.FISH_TYPE = B.FISH_TYPE
             WHERE B.FISH_NAME LIKE 'BASS' OR B.FISH_NAME LIKE 'SNAPPER')
