select A.TITLE, A.BOARD_ID,	B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
    DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD A 
    join USED_GOODS_REPLY B
    on  A.BOARD_ID = B.BOARD_ID
where MONTh(A.CREATED_DATE) = 10
    and YEAR(A.CREATED_DATE) = 2022
order by B.CREATED_DATE, A.TITLE